docker:
  image: yegor256/blog-image:0.0.1
assets:
  secrets.yml: "zerocracy/home#assets/blog/secrets.yml"
  id_rsa: "zerocracy/home#assets/blog/id_rsa"
  id_rsa.pub: "zerocracy/home#assets/blog/id_rsa.pub"
install: |
  rvm use ruby-2.7.7
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
merge:
  script: |
    LC_ALL=en_US.UTF-8 bundle exec rake
deploy:
  script: |
    export JEKYLL_ENV=production
    LC_ALL=en_US.UTF-8 bundle exec rake
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git config --global user.email "rultor@yegor256.com"
    git config --global user.name "Rultor"
    LC_ALL=en_US.UTF-8 jgd
