docker:
  image: yegor256/blog-image
assets:
  secrets.yml: "zerocracy/home#assets/blog/secrets.yml"
  id_rsa: "zerocracy/home#assets/blog/id_rsa"
  id_rsa.pub: "zerocracy/home#assets/blog/id_rsa.pub"
install: |
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  bundle install
deploy:
  script: |
    export JEKYLL_ENV=production
    LC_ALL=en_US.UTF-8 rake
    mkdir ~/.ssh
    mv ../id_rsa ../id_rsa.pub ~/.ssh
    chmod -R 600 ~/.ssh/*
    echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
    git config --global user.email "rultor@yegor256.com"
    git config --global user.name "Rultor"
    LC_ALL=en_US.UTF-8 jgd
