name: yegor256.com
url: https://www.yegor256.com
title: "Yegor Bugayenko"
author:
  name: "Yegor Bugayenko"
  email: yegor256@gmail.com
description: "Yegor Bugayenko"
copyright: "(c) Yegor Bugayenko, 2014-2021"
encoding: utf-8
timezone: America/San_Francisco

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

permalink: :year/:month/:day/:title.html
paginate: 16
paginate_path: "p/:num"
excerpt_separator: <!--more-->
exclude:
  - README.md
  - LICENSE.txt
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - httpd.conf
  - id_rsa.enc
  - s3cfg.enc
  - uml
  - node_modules

plugins:
  - jekyll-feed
  - jekyll-bits
  - jekyll-git-hash
  - jekyll-paginate
  - jekyll-plantuml
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-chatgpt-translate
  # - jekyll-related-posts

chatgpt-translate:
  threshold: 32
  source: en
  targets:
    -
      language: cn
      layout: chinese
      permalink: chinese/:year/:month/:day/:slug.html

# see https://github.com/alfanick/jekyll-related-posts
related:
  max_count: 5
  min_score: 0.1
  accuracy: 0.75

# jekyll-feed
feed:
  title: yegor256.com
  subtitle: Blog About Computers
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

# see https://github.com/pattex/jekyll-tagging
tag_page_layout: tag-index
tag_page_dir: tag

# http://jch.penibelst.de/
compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: all
  # endings: all
